#!/usr/bin/env python2

import pygame, sys, random, time, pickle, platform, numpy, os.path
from pygame.locals import *
pygame.init()

 
#@@@@@SETUP@@@@@#

#set speed
FPS = 10
fpsClock = pygame.time.Clock()

#set font
font = pygame.font.Font(None, 24)

#set volume
volume = 0.2

#colors
WHITE = (255, 255, 255)
GREEN = (0, 200, 0)
LIGHTGREEN = (0, 100 , 0)

#window size
size_w = 555		#width
size_h = 404		#height

#size + window name
surface = pygame.display.set_mode((size_w, size_h))
pygame.display.set_caption('Our Snake Game by: Matthew and Calib')

#images
background = pygame.image.load("images/background.png")					#background image
gameover = pygame.image.load("images/gameover.png")			#gameover image
new_record = pygame.image.load("images/new_record.png")		#new record
food = pygame.image.load("images/food.png")						#food icon
death = pygame.image.load("images/death.png")				#death
bonus = pygame.image.load("images/bonus.png")			#bonus
pause = pygame.image.load("images/pause.png")				#pause
icon = pygame.image.load('images/icon.png')			#game icon

#game icon 
pygame.display.set_icon(icon)

#snake create
snake = pygame.Surface((14, 14))			#create board
snake_testa = pygame.Surface((14, 14))	#create snake head
snake.fill(LIGHTGREEN)					#SnakeBody
snake_testa.fill(GREEN)					#SnakeHead
OS = platform.system()		#check OS

if OS == "Linux":
	from xdg import BaseDirectory
	path_data = BaseDirectory.save_config_path('snake_pygame/')	#where record file will be saved

	#create record file 
	if not os.path.exists(path_data):
		#file does not exist
		os.mkdir(path_data)								#create file

#START FUNCTIONS#

#before start and after restart
def init():
	global volume, points, snake_x, snake_y, min, max_x, max_y, direction, previous_direction, difficulty, record, bonus_icon, bonus_x, bonus_y
	
	try:
		record_file = open(path_data+"record.txt","r")		#check record
	except:
		record_file = open(path_data+"record.txt","w")		#if record file no exist
		record_file.write("0")
		record_file.close()
		record_file = open(path_data+"record.txt","r")
	
	record = int(record_file.read())					#open file and read
	record_file.close()								#close file
	pygame.mixer.music.load("Sound/music.ogg")		#music
	pygame.mixer.music.set_volume(volume)			#set volume
	pygame.mixer.music.play(-1)						#loops song 
	points = 0										#sets points to 0
	snake_x = [180, 165, 150, 135, 120, 105]			#create snake location x
	snake_y = [180]*6								#create snake location y
	min = 30										#snake minimum
	max_x = 525									#maximum snake width
	max_y = 375									#maximum snake height
	previous_direction = direction = 'right'			#which direction snake was facing
	difficolta = 0.05								#speed of snake on start
	genera_oggetti(snake_x[0],snake_y[0])				#creates it all
	bonus_icon = '0'
	bonus_x = bonus_y = 800
	
#funzione che genera gli oggetti
def genera_oggetti(snake_x, snake_y):
	global mela_x, mela_y, teschio_x, teschio_y, bonus_x, bonus_y		#esporto le variabili per renderle usabili anche al di fuori della funzione

	#genero casualmente le coordinate della mela e del teschio indicando i limiti minimi e massimi
	#l'algoritmo che ho usato fa in modo che la mela e il serpente, vengano generati nella stessa linea del serpente
	#perche' il serpente fa movimenti di 15pixel, quindi l'operazione 15*(min/15) e' uguale a 30 e questa e' la coordinata minina che possono assumere la mela o il teschio
	#invece l'operazione 15*((max_x/15)-1) e' uguale a 510 e questa e' la coordinata massima che il teschio e la mela possono assumere, essendo gli oggetti grandi 15px, 
	#sono costretto a mettere come coordinate massime di spawn 15px in meno, perche' altrimenti uscirebbe fuori dal campo di gioco
	mela_x = 15*(random.randint((min/15), ((max_x/15)-1)))		
	mela_y = 15*(random.randint((min/15), ((max_y/15)-1)))
	teschio_x = 15*(random.randint((min/15), ((max_x/15)-1)))
	teschio_y = 15*(random.randint((min/15), ((max_y/15)-1)))
	
	#adesso verifico che il teschio non spawna troppo vicino al serpente per evitare di morire inevitabilmente
	while ( ((teschio_x >= snake_x-90 and teschio_x <= snake_x+90) and (teschio_y >= snake_y-90 and teschio_y <= snake_y+90)) or (teschio_x == mela_x and teschio_y == mela_y) ):
		teschio_x = 15*(random.randint((min/15), ((max_x/15)-1)))
		teschio_y = 15*(random.randint((min/15), ((max_y/15)-1)))
	
	genera_num = random.randint(1, 40)			#genero un numero tra 1 e 40 se esce 1 allora faccio comparire il bonus
	if genera_num == 1:
		bonus_x = 15*(random.randint((min/15), ((max_x/15)-1)))
		bonus_y = 15*(random.randint((min/15), ((max_y/15)-1)))
		
		while ((bonus_x == teschio_x and bonus_y == teschio_y) or (bonus_x == mela_x and bonus_y == mela_y)):
			bonus_x = 15*(random.randint((min/15), ((max_x/15)-1)))
			bonus_y = 15*(random.randint((min/15), ((max_y/15)-1)))
	else:
		bonus_x = bonus_y = 800

#funzione che visualizza gli oggetti a schermo
def mostra():
	global direction
	
	punteggio = font.render('Punteggio: %d' % (points), True, WHITE)
	highscore = font.render('Record: %d' % (record), True, WHITE)
	vol = font.render('Volume: %d' % (volume*5), True, WHITE)
	bonus = font.render('Bonus: [      ]', True, WHITE)
	surface.blit(background, (0, 0))	
	surface.blit(punteggio, (30, 8))
	surface.blit(highscore, (430, 8))
	surface.blit(vol, (30, 382))
	surface.blit(bonus, (430, 382))
	
	for i in range(1,len(snake_x)):					#mostro tutti i blocchi del corpo dello snake
		surface.blit(snake, (snake_x[i], snake_y[i]))
	surface.blit(snake_testa, (snake_x[0], snake_y[0]))	#mostro la testa dello snake
	
	surface.blit(mela, (mela_x, mela_y))				#mostro la mela
	surface.blit(teschio, (teschio_x, teschio_y))			#mostro il teschio
	surface.blit(dimezza, (bonus_x, bonus_y))
	if bonus_icon == '1':							#se ho preso il bonus allora mostro l'icona
		surface.blit(dimezza, (500, 384))
	
	pygame.display.update()							#aggiorno tutto
	fpsClock.tick(FPS)


#funzione che salva il nuovo record all'interno dell'apposito file
def scrivi():
	record_file = open(path_data+"record.txt","w")		#apro il file record.txt in sola scrittura e lo assegno alla variabile record
	record_file.write(str(int(punti)))					#converto la variabile "punti" in stringa e scrivo il contenuto nel file record.txt
	record_file.close()							#chiudo il file precedentemente aperto
	
	surface.blit(nuovo_record, (0, 0))				#mostro la schermata di gameover
	pygame.display.update()						#aggiorno lo schermo
	
	for event in pygame.event.get():				#controllo la pressione del tasto
		if event.key == K_r:						#se premo "r" chiama la funzione inizializzazione()
			init()
		elif event.key == K_ESCAPE:				#se premo "ESC" vai alla funzione game_over()
			game_over()

#funzione che mostra la schermata di pausa
def pausa():
	surface.blit(pausa_img, (0, 0))				#mostro la schermata di pausa
	pygame.display.update()						#aggiorno lo schermo

#CHIEDO SE SI VUOLE RICOMINCIARE IL GIOCO
def restart():
	pygame.mixer.music.stop()						#interrompo il file audio
	
	#controllo se l'attuale punteggio e' piu' alto dell'attuale record
	if punti > record:
		scrivi()		#se entro dentro a questo if significa che ho fatto un nuovo record quindi chiamo l'apposita funzione
	else:
		surface.blit(gameover_img, (0, 0))		#mostro la schermata di gameover
		pygame.display.update()				#aggiorno lo schermo
		for event in pygame.event.get():		#controllo la pressione del tasto
			if event.type == QUIT:			#se viene premuto il tasto chiudi della finestra, vai alla funzione game_over()
				game_over()
		
			#controllo quali tasti vengono premuti
			elif event.type == KEYDOWN:
				if event.key == K_r:				#se premo "r" chiama la funzione inizializzazione()
					init()

				elif event.key == K_ESCAPE:		#se premo "ESC" vai alla funzione game_over()
					game_over()
	
#questa funzione chiude pygame e tutti i moduli caricati
def game_over():
	pygame.quit()
	sys.exit()


#INIZIO PROGRAMMA
init()			#chiamo la funzione per inizializzare tutte le variabili

while True:
	#controllo in base ai punti raggiunti quale livello di difficolta' devo settare
	if points < 10:
		dificulty = 0.05
	elif points < 30:
		dificulty = 0.045
	elif points < 50:
		dificulty = 0.04
	elif points < 80:
		dificulty = 0.035
	elif points > 80:
		dificulty = 0.03
	
	incremento_punti = 1+round(points*dificulty)		#algoritmo per l'incremento del punteggio, la funziona round arrotonda il numero togliendo la parte dopo la virgola
	
	time.sleep(dificulty)	#e' il tempo che trascorre prima di mostrare il nuovo frame (piu' il tempo e' basso maggiore e' la velocita')
	
	mostra()				#creates it all
	
	for event in pygame.event.get():		#controllo la pressione del tasto
		if event.type == QUIT:			#se viene premuto il tasto chiudi della finestra, vai alla funzione game_over()
			game_over()
		
		#controllo quali tasti vengono premuti
		elif event.type == KEYDOWN:
			#se premo il tasto "freccia destra" o "d", e l'attuale direzione non e' "sinistra" e se non sono nella schermata di gameover, allora la nuova direzione e' "destra" (lo stesso discorso vale per gli altri if)
			if ((((event.key == K_RIGHT or event.key == K_d) and direzione != 'sinistra') and direzione != 'gameover') and direzione != '0'):
				#controllo se il serpente si e' spostato, cosi' da evitare che spostandosi velocemente prima su/giu e poi a destra, 
				#il serpente non fa in tempo a spostarsi su/giu andando di conseguenza solo a destra causando il gameover
				if spostamento_effettuato == '1':
					direzione_precedente = direzione = 'destra'
					spostamento_effettuato = '0'
					
			elif ((((event.key == K_LEFT or event.key == K_a) and direzione != 'destra') and direzione != 'gameover') and direzione != '0'):
				if spostamento_effettuato == '1':
					direzione_precedente = direzione = 'sinistra'
					spostamento_effettuato = '0'
					
			elif ((((event.key == K_DOWN or event.key == K_s) and direzione != 'su') and direzione != 'gameover') and direzione != '0'):
				if spostamento_effettuato == '1':
					direzione_precedente = direzione = 'giu'
					spostamento_effettuato = '0'
					
			elif ((((event.key == K_UP or event.key == K_w) and direzione != 'giu') and direzione != 'gameover') and direzione != '0'):
				if spostamento_effettuato == '1':
					direzione_precedente = direzione = 'su'
					spostamento_effettuato = '0'
					
			elif (event.key == K_p and direzione != 'gameover'):
				if direzione == '0':
					direzione = direzione_precedente
				else:
					direzione = '0'
			
			elif event.key == K_KP_PLUS or event.key == K_PLUS:	#controllo se viene premuto il tasto + della tastiera o del numpad
				if volume < 1.0:			
					volume += 0.2			#alzo il volume
				elif volume > 1.0:
					volume = 1.0
				pygame.mixer.music.set_volume(volume)
			
			elif event.key == K_KP_MINUS or event.key == K_MINUS:	#controllo se viene premuto il tasto - della tastiera o del numpad
				if volume > 0.0:
					volume -= 0.2			#abbasso il volume
				elif volume < 0.0:
					volume = 0.0
				pygame.mixer.music.set_volume(volume)
				
			elif event.key == K_ESCAPE:
				game_over()
				
			elif event.key == K_r:
				init()
				
			elif (event.key == K_SPACE and  bonus_icon == '1' and direzione != 'gameover' and direzione != '0'):
				bonus_icon = '0'
				i = (len(snake_x)-1)
				meta_snake = (i / 2)
				while meta_snake < i:
					del snake_x[i]
					i -= 1
			
	
	if direzione == '0':				#se direzione e' uguale a '0' allora e' stato premuto il tasto "p" quindi vai alla funzione pausa()
		pausa()
		
	elif direzione == 'gameover':		#se direzione e' uguale a "gameover" allora ho perso quindi vai alla funzione restart()
		restart()


	#se se la variabile "direzione" non soddisfa le 2 condizioni precedenti allora si puo' continuare
	else:
		#algoritmo per lo spostamento del serpente
		i = len(snake_x)-1
		while i > 0:
			snake_x[i] = snake_x[i-1]		#il blocco del corpo prende le coordinate del blocco precedente
			snake_y[i] = snake_y[i-1]	
			i -= 1					#decremento l'indice per controllare un altro blocco
				
		#muovo il serpente in base al tasto che ho premuto
		if direzione == 'destra':
			snake_x[0] += 15					#sposto il serpente
			spostamento_effettuato = '1'		#segnalo che il serpente ha effettuato lo spostamento
		elif direzione == 'sinistra':
			snake_x[0] -= 15
			spostamento_effettuato = '1'
		elif direzione == 'giu':
			snake_y[0] += 15
			spostamento_effettuato = '1'
		elif direzione == 'su':
			snake_y[0] -= 15
			spostamento_effettuato = '1'

		i = len(snake_x)-1
		#controllo se il serpente colpisce la mela
		if snake_x[0] == mela_x and snake_y[0] == mela_y:
			punti += incremento_punti					#aggiunto un punto
			genera_oggetti(snake_x[0],snake_y[0])			#chiamo la funzione per generare gli oggetti				
			#aggiungo un nuovo blocco al corpo del serpente per allungarlo
			snake_x.append(800)
			snake_y.append(800)

		#controllo se il serpente prende l'oggetto bonus	
		if snake_x[0] == bonus_x and snake_y[0] == bonus_y:		#se colpisco l'oggetto bonus
			bonus_icon = '1'								#abilito l'icona bonus in basso a sinistra
			punti += 5+round(punti*difficolta)					#aggiunto 5 punti piu' un punteggio proporzinale alla difficolta' e i punti attuali
			genera_oggetti(snake_x[0],snake_y[0])				#rigenero gli oggetti
			bonus_x = bonus_y = 800						#faccio scomparire l'oggetto bonus dalla schermata
			snake_x.append(800)
			snake_y.append(800)
			
		#controllo se il serpente colpisce il teschio
		if snake_x[0] == teschio_x and snake_y[0] == teschio_y:
			direzione = 'gameover'
		
		#verifico se il serpente "si morde"
		while i > 4:
			if snake_x[0] == snake_x[i] and snake_y[0] == snake_y[i]:
				direzione = 'gameover'
			i -= 1
		
		#controllo se il serpente esce dal bordo
		if ((snake_x[0] >= max_x) or (snake_x[0] < min) or (snake_y[0] >= max_y) or (snake_y[0] < min)):
			direzione = 'gameover'
